### PR TITLE
[Breq 1547] Voithos Docs Octavia Deployment

### PR DESCRIPTION
**Pull request by waqasnazir03**
This PR addresses #1547.

### CODE REVIEW

**Review by ruthrosals — APPROVED** [review]
only 2 comments:
docs/offline-openstack-with-iscsi.md

# Build And Create Octavia Amphora
This is required for creating loadbalancers.
- [**Octavia Amphorha Create**](/openstack-octavia-amphora.html)n  > line 58 - there is  typo remove the extra 'h' in Amphorha 

docs/openstack-octavia-post-deployment.md

openstack flavor create --vcpus 1 --ram 1024 "amphora" --private  > line 35 - it is just visual if the name of the flavor "amphora" can be positioned at the beginning or end of the command something like  `openstack flavor create --private --vcpus 1 --ram 1024 "amphora" `

**Comment by waqasnazir03** [comment]
@ruthrosals: I have addressed your comments. Please have another look.
@kylep: I have added amphora images on s3 and made some changes in code and docs.

**Review by ruthrosals — APPROVED** [review]
It looks good to me.

**Review by ruthrosals — APPROVED** [review]
It looks good to me.

**Review by kylep — APPROVED** [review]

**Pull request merged**
