### PR TITLE
Breq 1175 migrate windows ip bootstrap

### PR DESCRIPTION
**Pull request by kylep**

### CODE REVIEW

**Review by ruthrosals — COMMENTED** [review]
I found the same typo, I noticed you created another commit to fix the typo on the function Copy-VoithosModuleToBootPartition.  Now it looks fine.

**Review by ruthrosals — COMMENTED** [review]
Only lines 255 and 256 I noticed that values false are lowercase. Just change first letter to capital False.

**Review by ruthrosals — COMMENTED** [review]
It will work but if you want to change parameter values from true to True or from false to False,  lines 229 - 233

**Comment by kylep** [comment]
Comments addressed, thanks

**Pull request merged**
